name:                MathProgHs
version:             0.1.0.0
github:              "prsteele/MathProgHs"
license:             BSD3
author:              "Patrick Steele"
maintainer:          "steele.pat@gmail.com"
copyright:           "2018 Patrick Steele"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prsteele/MathProgHs#readme>

dependencies:
  - base >= 4.7 && < 5
  - glpk-hs >= 0.1.0.0 && < 0.2
  - mtl >= 2.2.2 && < 2.3
  - containers >= 0.5.11 && < 0.6

library:
  source-dirs: src

executables:
  MathProgHs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    extra-libraries:
      - glpk
    dependencies:
      - MathProgHs

tests:
  MathProgHs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    extra-libraries:
      - glpk
    dependencies:
    - MathProgHs
