name:                math-programming
version:             0.3.0
github:              "prsteele/math-programming"
license:             BSD3
author:              "Patrick Steele"
maintainer:          "steele.pat@gmail.com"
copyright:           "2018 Patrick Steele"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A library for formulating and solving math programs.
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prsteele/math-programming#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - containers
  - text

library:
  source-dirs: src
  ghc-options:
    - -Wall

tests:
  math-programming-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - math-programming
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
